In [10]:
#Imports
import pandas as pd
import numpy as np
import statistics
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [11]:
imputer = SimpleImputer(strategy='median')
scaler = StandardScaler()

num_pipeline = Pipeline([
        ('imputer', imputer),
        ('std_scaler', scaler),
    ]) #Pipeline for numerical features

def process_data(data_input):
    
    catergorical_labels = "name" 
    num_attribs = data_input.drop(catergorical_labels, axis=1) #Use only numerical features
  
    return num_pipeline.fit_transform(num_attribs)

In [12]:
#Reading the data
data = pd.read_excel("database.xlsx")
data

,playerId,teamName,playedPositions,positionText,rating,totalPassesPerGame,accurateCrossesPerGame,accurateLongPassPerGame,accurateThroughBallPerGame,passSuccess,...,tacklePerGame,interceptionPerGame,foulsPerGame,offsideWonPerGame,clearancePerGame,wasDribbledPerGame,outfielderBlockPerGame,goalOwn,age,value
0,279575,Flamengo,-AMC-AML-AMR-FW-,Forward,7.400833,22.875000,0.041667,0.291667,0.125000,74.499089,...,0.750000,0.458333,1.750000,0.000000,1.000000,0.708333,0.041667,0,29,"4,50 mi. €"
1,16886,Atletico MG,-AMC-AML-AMR-FW-,Forward,7.397143,23.685714,0.171429,0.800000,0.028571,75.633293,...,0.342857,0.114286,1.542857,0.000000,0.571429,0.428571,0.028571,0,33,"2,50 mi. €"
2,318302,Red Bull Bragantino,-AML-AMR-,Forward,7.256000,30.566667,1.333333,2.200000,0.100000,81.897492,...,0.500000,0.433333,0.600000,0.000000,0.266667,0.933333,0.200000,0,22,"5,00 mi. €"
3,356785,America MG,-AMC-AMR-,Forward,7.247742,22.709677,0.870968,0.870968,0.193548,72.585227,...,0.870968,0.354839,0.903226,0.032258,0.225806,1.064516,0.000000,0,25,700 mil €
4,384431,Gremio,-AML-AMR-,Forward,7.155172,31.862069,0.517241,0.827586,0.103448,83.982684,...,1.068966,0.551724,0.517241,0.000000,0.275862,1.137931,0.034483,0,22,"7,50 mi. €"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362,377097,Chapecoense AF,-MC-,Defender,6.160625,12.937500,0.125000,0.687500,0.000000,79.710145,...,0.750000,0.562500,0.750000,0.000000,0.562500,0.312500,0.187500,0,22,300 mil €
363,21613,Fortaleza,-AMR-FW-,Forward,6.158800,5.760000,0.080000,0.160000,0.040000,65.277778,...,0.280000,0.080000,0.800000,0.040000,0.360000,0.280000,0.000000,0,36,500 mil €
364,120762,America MG,NaN,Forward,6.135500,8.050000,0.250000,0.350000,0.000000,78.260870,...,0.500000,0.250000,0.350000,0.000000,0.200000,0.150000,0.000000,0,37,250 mil €
365,397825,Corinthians,-DMC-,Midfielder,6.127500,11.562500,0.000000,0.437500,0.000000,82.162162,...,0.312500,0.125000,0.437500,0.062500,0.875000,0.312500,0.312500,0,20,800 mil €
366,397586,Juventude,NaN,Forward,6.061250,2.937500,0.312500,0.125000,0.000000,70.212766,...,0.187500,0.062500,0.375000,0.000000,0.062500,0.125000,0.000000,0,21,700 mil €

In [13]:
#Data cleaning
def set_value(value):
    number, unit, _ = value.split(" ")
    number = float(number.replace(",","."))
    unit = 10e5 if unit == "mi." else 10e2
    return number*unit

data["value"] = [set_value(valor) for valor in data["value"]]

In [14]:
cleaned_data = data.drop(['playerId', 'teamName', 'playedPositions', 'positionText', "value", 'age'], axis=1)
cleaned_data = cleaned_data.reset_index().drop("index", axis=1)
cleaned_data.columns

Index(['rating', 'totalPassesPerGame', 'accurateCrossesPerGame',
       'accurateLongPassPerGame', 'accurateThroughBallPerGame', 'passSuccess',
       'name', 'goal', 'assistTotal', 'shotsPerGame', 'keyPassPerGame',
       'dribbleWonPerGame', 'foulGivenPerGame', 'offsideGivenPerGame',
       'dispossessedPerGame', 'turnoverPerGame', 'apps', 'subOn', 'minsPlayed',
       'tacklePerGame', 'interceptionPerGame', 'foulsPerGame',
       'offsideWonPerGame', 'clearancePerGame', 'wasDribbledPerGame',
       'outfielderBlockPerGame', 'goalOwn'],
      dtype='object')

In [15]:
#Data preprocess
prep_data = process_data(cleaned_data)
prep_data

array([[ 3.19274557, -0.4004632 , -0.67759817, ...,  0.14120987,
        -0.63683477, -0.19009938],
       [ 3.17709287, -0.34180155, -0.30561022, ..., -0.51907674,
        -0.69128031, -0.19009938],
       [ 2.57845278,  0.15609027,  3.02521768, ...,  0.6722489 ,
         0.02146119, -0.19009938],
       ...,
       [-2.17401025, -1.47317026, -0.08036981, ..., -1.17655363,
        -0.81007055, -0.19009938],
       [-2.20794126, -1.21901285, -0.79704385, ..., -0.79302544,
         0.48919779, -0.19009938],
       [-2.4889325 , -1.84310044,  0.0987987 , ..., -1.23555796,
        -0.81007055, -0.19009938]])

In [16]:
#SVD
u, s, vt = np.linalg.svd(prep_data, full_matrices=False)

In [17]:
ut = u[:,:5] #Selecting 5 most "relevant" columns
ut = ut / np.linalg.norm(ut, axis =1).reshape(-1,1) #Normalizing 
products = ut.dot(ut.transpose()) #Matrix containing player similarity probability

In [18]:
products.shape #Checking shape

(367, 367)

In [33]:
#Testing
index = cleaned_data.index #Players index

In [34]:
def get_smilar_players_ordered_by_value(player_name, similar_players_number):
    
    player_index = index[cleaned_data["name"] == player_name][0] #Index of the player to be compared
    
    player_similarity_row = products[player_index] #Player similarity vector
    
    selection_value = -1 * (similar_players_number + 1)
    similar_player_index = np.argpartition(player_similarity_row, selection_value)[selection_value:] #Selecting B most similar players, including the given one
    similar_player_index_no_main = similar_player_index[similar_player_index != player_index] #Similar player without the given one
    mean_value = statistics.mean(data.iloc[similar_player_index_no_main]["value"]) #Mean value of similar players excluding the given one
    mean_age = statistics.mean(data.iloc[similar_player_index_no_main]["age"]) #Mean age of similar players excluding the given one
    mean_age_value = mean_age * mean_value
    
    return pd.DataFrame( \
        sorted(
            [ \
                [player["name"], player["teamName"], player["age"], player["value"]/10e2, round((1 - (player["value"] * player["age"] / mean_age_value))*100, 2)]  
            for idx, player in data.iloc[similar_player_index_no_main].iterrows()], \
        key=lambda x: x[4], reverse=True), \
    columns=["Name", "Team", "Age", "Value (TEUR)", "Possible gain %"]) #Returns a dataframe containig similar player's Name, Team, Age, Value and Possible Gain, ordered by Posible Gain

In [35]:
get_smilar_players_ordered_by_value("Weverton", 10)

                Name                  Team  Age  Value (TEUR)  Possible gain %
0            Keiller        Chapecoense AF   23          50.0            95.93
1             Daniel         Internacional   26          50.0            95.40
2      Marcelo Boeck             Fortaleza   35         200.0            75.24
3       Felipe Alves             Fortaleza   32         650.0            26.44
4      Marcelo Carné             Juventude   30         900.0             4.51
5  Douglas Friedrich             Juventude   31         900.0             1.32
6         João Paulo        Chapecoense AF   25        1400.0           -23.79
7            Richard                 Ceara   26        1500.0           -37.93
8        Diego Alves              Flamengo   35        1500.0           -85.68
9             Santos  Athletico Paranaense   30        2500.0          -165.26

In [37]:
get_smilar_players_ordered_by_value("Dudu", 10)

,Name,Team,Age,Value (TEUR),Possible gain %
0,Rossi,Bahia,27,1000.0,62.94
1,David Terans,Athletico Paranaense,25,1400.0,51.97
2,Rafael Gava,Cuiaba,27,1300.0,51.83
3,Nikão,Athletico Paranaense,27,1400.0,48.12
4,Vina,Ceara,31,1500.0,36.18
5,Keno,Atletico MG,30,3000.0,-23.52
6,Gustavo Scarpa,Palmeiras,26,3500.0,-24.89
7,Vitinho,Flamengo,26,4000.0,-42.73
8,Artur,Red Bull Bragantino,22,5000.0,-50.97
9,Jefferson Savarino,Atletico MG,23,5500.0,-73.61